---
- name: Get VM Details and Store as JSON
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Gather Azure VM Info
      azure_rm_virtualmachine_info:
        resource_group: "azeu-it-rg"
        name: "azues15s3sy1"
      register: vm_info

    - name: Store VM details as JSON
      copy:
        content: "{{ vm_info | to_nice_json }}"
        dest: "vm_info_output.json"